### ISSUE TITLE
Update ember-cli-babel to 6

### ISSUE THREAD

**Issue by boris-petrov** [jerel/ember-storage#9]
Hi, I love your plugin, however it's one of the few that are still using `ember-cli-babel` 5 in our project. Using version 6 would allow the removal of `ember-cli-shims` as well as fix some deprecation warnings. More information on that could be seen [here](https://emberjs.com/blog/2017/11/20/ember-2-17-released.html).

P.S. See more issues of that kind:

https://github.com/mharris717/ember-drag-drop/issues/121

**Comment by jerel** [comment]
Hey @boris-petrov, sorry for the slow response here. Would you care to open a pull request? I'd be happy to merge the upgrade.

**Comment by boris-petrov** [comment]
@jerel - thanks for the response! I have never written an ember plugin and I have no idea how to upgrade one unfortunately. I might try at some point but it won't be that soon. I'll be happy if anyone else steps up to the task.

Also, thanks for the project!

**Comment by chvonrohr** [comment]
hey, could you check my PR and - if ok - merge? 
A new release would be appreciated  ;)

**Comment by chvonrohr** [comment]
@jerel reminder....

**Comment by chvonrohr** [comment]
@jerel reminder nr. 2 (?)
